data:
  client_cnt: 10
  poison_client_cnt: 0
  iid: True
  poison_rate: .4
  batch_size: 100
  label_col: Attack_type

object: multi

train:
  opt: Adam
  opt_params:
    lr: 0.01
    weight_decay: 0.0001
  drop_out: 0.2
  global_epoch: 10
  client_epoch: 1

path:
  model_save_path: ./models/iid_K10_Km0_Multi.pth
  report_save_path: ./models/iid_K10_Km0_Multi.json